/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bitharis.panos.hkrcaretaker.org.bitharis.panos.entities;

import java.io.Serializable;

import java.util.Collection;



public class Employees implements Serializable {

    private static final long serialVersionUID = 1L;

    private int empId;

    private String empFirstname;

    private String empLastname;

    private String empUsername;

    private String empPassword;

    private String empEmail;

    private String empPhone;

    private boolean empRegistered;

    private Managers managersManId;
    //following are autogenerated by wizard
    

    private Collection<Tasks> tasksCollection;
    private Collection<Notes> notesCollection;
    private Collection<EmployeeSchedule> employeeScheduleCollection;

    public Employees() {
    }

    public Employees(Integer empId) {
        this.empId = empId;
    }

    public Employees(String empFirstname, String empLastname, String empUsername, String empPassword, String empEmail, String empPhone, Managers managers) {

        this.empFirstname = empFirstname;
        this.empLastname = empLastname;
        this.empUsername = empUsername;
        this.empPassword = empPassword;
        this.empEmail = empEmail;
        this.empPhone = empPhone;
        this.managersManId = managers;

    }

    public Employees(Managers managers,String empFirstname, String empLastname, String empUsername, String empPassword, String empEmail, String empPhone, boolean empRegistered) {
        this.empId = empId;
        this.empFirstname = empFirstname;
        this.empLastname = empLastname;
        this.empUsername = empUsername;
        this.empPassword = empPassword;
        this.empEmail = empEmail;
        this.empPhone = empPhone;
        this.empRegistered = empRegistered;
        this.managersManId = managers;
    }

    public int getEmpId() {
        return empId;
    }

    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    public String getEmpFirstname() {
        return empFirstname;
    }

    public void setEmpFirstname(String empFirstname) {
        this.empFirstname = empFirstname;
    }

    public String getEmpLastname() {
        return empLastname;
    }

    public void setEmpLastname(String empLastname) {
        this.empLastname = empLastname;
    }

    public String getEmpUsername() {
        return empUsername;
    }

    public void setEmpUsername(String empUsername) {
        this.empUsername = empUsername;
    }

    public String getEmpPassword() {
        return empPassword;
    }

    public void setEmpPassword(String empPassword) {
        this.empPassword = empPassword;
    }

    public String getEmpEmail() {
        return empEmail;
    }

    public void setEmpEmail(String empEmail) {
        this.empEmail = empEmail;
    }

    public String getEmpPhone() {
        return empPhone;
    }

    public void setEmpPhone(String empPhone) {
        this.empPhone = empPhone;
    }

    public boolean getEmpRegistered() {
        return empRegistered;
    }

    public void setEmpRegistered(boolean empRegistered) {
        this.empRegistered = empRegistered;
    }

    public Managers getManagersManId() {
        return managersManId;
    }

    public void setManagersManId(Managers managersManId) {
        this.managersManId = managersManId;
    }


    
}
